//Rhye
#ifndef CVRHYES_H
#define CVRHYES_H

// rhyes.h
#define EARTH_X					(176)
#define EARTH_Y					(84)
#define CATAPULT_X				(70)
#define CATAPULT_Y				(82)
#define MAX_COM_SHRINE			(20)
#define NUM_MAJOR_PLAYERS		(48)
#define NUM_MAJOR_LEADERS		(55) // srpt
#define NUM_CIV_DESC			(68) // srpt
#define SLAVERY					(11)
#define PERSECUTION				(23)
#define PROMOTION_MERCENARY		(57)
#define PROMOTION_DISCIPLINE	(0)
#define UNIT_PROSECUTOR			(5)
#define UNIT_PROSECUTOR_CLASS	(5)
#define NUM_BARB_REGIONS 		(11)
#define JUNGLE			 		(1) // srpt Funan UP
//#define ASOKA					(11) // srpt Mauryan UP
//#define QIN_SHI_HUANG			(31) // srpt Qin UP
#define UNIT_SETTLER			(0) // srpt Slavery unit capture
#define UNIT_WORKER				(1)
#define UNIT_SLAVE				(2)
//edead
enum MyCivs
{
	ANTIGONIDS, // 0
	SELEUCIDS, // 1
	EGYPT, // 2
	CARTHAGE, // 3
	MAURYANS, // 4
	KALINKA, // 5
	QIN, // 6
	GOJOSEON, // 7
	NUBIA, // 8
	SABA, // 9
	PANDYANS, // 10
	PONTUS, // 11
	CELTS, // 12
	ROME, // 13
	VIETNAM, // 14
	TOCHARIANS, // 15
	BACTRIA, // 16
	HAN, // 17
	SATAVAHANA, // 18
	ARMENIA, // 19
	MACCABEES, // 20
	PARTHIA, // 21
	DACIA, // 22
	GOGURYEO, // 23
	AXUM, // 24
	KUSHANS, // 25
	FUNAN, // 26
	JIN, // 27
	SASSANIDS, // 28
	YAMATO, // 29
	GUPTA, // 30
	BYZANTINES, // 31
	VISIGOTHS, // 32
	VANDALS, // 33
	OSTROGOTHS, // 34
	FRANKS, // 35
	CHALUKYANS, // 36
	LOMBARDS, // 37
	GOKTURKS, // 38
	SRIVAJAYA, // 39
	KHAZARS, // 40
	TIBET, // 41
	TANG, // 42
	ARABS, // 43
	GHANA,
	NOMAD,
	NOMAD2,
	NOMAD3,
	INDEPENDENT,
	INDEPENDENT2,
	INDEPENDENT3,
	BARBARIAN,
};

enum MyLeaders
{
	ANTIGONUS, // 0
	SELEUCUS, // 1
	PTOLEMY, // 2
	HANNIBAL, // 3
	ASOKA, // 4
	KHARAVELA, // 5
	QIN_SHI_HUANG, // 6
	DANGUN, // 7
	ARRAKKAMANI, // 8
	TUBA_ABU, // 9
	NEDUNJ, // 10
	MITHRIDATES, // 11
	VERCINGETORIX, // 12
	CAESAR, // 13
	THUC_PHAN, // 14
	SAPADBIZES, // 15
	DEMETRIUS, // 16
	WU, // 17
	SATAKARNI, // 18
	TIGRANES, // 19
	SIMON_MACCABEE, // 20
	ARSACES, // 21
	DECEBAL, // 22
	GWANGGAETO, // 23
	EZANA, // 24
	KANISHKA, // 25
	LIEUYE, // 26
	SIMA_YAN, // 27
	SHAPUR, // 28
	JINGU, // 29
	CHANDRAGUPTA, // 30
	JUSTINIAN, // 31
	ALARIC, // 32
	GAISERIC, // 33
	THEODORIC, // 34
	CHARLEMAGNE, // 35
	PULAKESI, // 36
	LIUTPRAND, // 37
	BILGE, // 38
	SARAMATUNGGA, // 39,
	BULAN, // 40
	SONGSTEN_GAMPO, // 41
	TAIZONG, // 42
	ABU_BAKR, // 43
	SHAKA, // 44
	SYPHAX, // 45
	ATHEAS,  // 46
	ZHAO_TUO, // 47
	PUSYAMITRA, // 48
	LEADER_ROURAN, // 49
	ATILLA, // 50
	LIU_BEI, // 51
	SUN_QUAN, // 52
	POMPEY, // 53
	TARIQ, // 54
	BARBARIAN_LEADER,
	MINOR_LEADER,
	NUM_LEADERS
};

enum MyReligions
{
	JUDAISM,
	ZOROASTRIANISM,
	HINDUISM,
	BUDDHISM,
	CONFUCIANISM,
	HELLENISM,
	TAOISM,
	JAINISM,
	CHRISTIANITY,
	MANICHAEISM,
	ISLAM,
	NUM_RELIGIONS
};

enum MyCorporations
{
	GRAINMERCHANTS,
	FISHMERCHANTS,
	CLOTHMERCHANTS,
	SPICEMERCHANTS,
	ARTISANS,
	TRADESMEN,
	NUM_CORPORATIONS
};

enum MyResources
{
	BONUS_HORSE,
	BONUS_IRON,
	BONUS_COPPER,
	BONUS_SULPHUR,
	BONUS_MARBLE,
	BONUS_STONE,
	BONUS_CLAM,
	BONUS_CRAB,
	BONUS_COW,
	BONUS_DEER,
	BONUS_FISH,
	BONUS_PIG,
	BONUS_RICE,
	BONUS_SHEEP,
	BONUS_WHEAT,
	BONUS_BARLEY,
	BONUS_DYE,
	BONUS_FUR,
	BONUS_GOLD,
	BONUS_INCENSE,
	BONUS_SILK,
	BONUS_SILVER,
	BONUS_SPICES,
	BONUS_SUGAR,
	BONUS_WINE,
	BONUS_WHALE,
	BONUS_HEMP,
	BONUS_COTTON,
	BONUS_HONEY,
	BONUS_SALT,
	BONUS_OLIVES,
	BONUS_CITRUS,
	BONUS_APPLE,
	BONUS_DATES,
	BONUS_GEMS,
	BONUS_PEARL,
	BONUS_IVORY,
	BONUS_OPIUM,
	BONUS_CINNAMON,
	BONUS_SORGHUM,
	BONUS_CHARCOAL,
	BONUS_CAMEL,
	BONUS_TIMBER,
	BONUS_TEA,
	BONUS_HELLENISM,
	BONUS_JAINISM,
	BONUS_HINDUISM,
	BONUS_BUDDHISM,
	BONUS_TAOISM,
	BONUS_CONFUCIANISM,
	BONUS_ZOROASTRIANISM,
	BONUS_JUDAISM,
	BONUS_CHRISTIANITY,
	BONUS_MANICHAEISM,
	BONUS_ISLAM,
	NUM_BONUSES
};

enum MyCivics
{
	CIVIC_DESPOTISM,
	CIVIC_MONARCHY,
	CIVIC_OLIGARCHY,
	CIVIC_EMPIRE,
	CIVIC_THEOCRACY,
	CIVIC_TRIBAL_CUSTOM,
	CIVIC_TYRANNY,
	CIVIC_VASSALAGE,
	CIVIC_RELIGIOUS_LAW,
	CIVIC_BUREAUCRACY,
	CIVIC_TRIBAL_LEVY,
	CIVIC_SLAVERY,
	CIVIC_CASTE_SYSTEM,
	CIVIC_SERFDOM,
	CIVIC_WAGE_LABOR,
	CIVIC_DECENTRALIZATION,
	CIVIC_AGRARIANISM,
	CIVIC_TRADE_ECONOMY,
	CIVIC_PATRONAGE,
	CIVIC_MILITARY_ECONOMY,
	CIVIC_PAGANISM,
	CIVIC_DYNASTIC_CULT,
	CIVIC_STATE_RELIGION,
	CIVIC_MILITANCY,
	CIVIC_SYNCRETISM
};

enum MyTechs
{
	ARCHERY,
	SIEGE_ENGINES,
	MARKSMANSHIP,
	AGRICULTURE,
	HORTICULTURE,
	CROP_ROTATION,
	CASTE_SYSTEM,
	CALENDAR,
	AGRARIANISM,
	THE_PLOUGH,
	ANIMAL_HUSBANDRY,
	ELEPHANT_TRAINING,
	HORSEMANSHIP,
	SELECTIVE_BREEDING,
	CAVALRY_TACTICS,
	THE_STIRRUP,
	HORSE_ARCHERY,
	FISHING,
	SAILING,
	NAVAL_WARFARE,
	STERN_RUDDER,
	NAVIGATION,
	ASTROLABE,
	POTTERY,
	CONSTRUCTION,
	MASONRY,
	BRIDGE_BUILDING,
	ENGINEERING,
	FORTIFICATION,
	SANITATION,
	MACHINERY,
	MEDICINE,
	ARCHITECTURE,
	PAPER,
	EDUCATION,
	PRINTING_PRESS,
	BUREAUCRACY,
	LUXURY_TRADE,
	MONARCHY,
	VASSALAGE,
	SERFDOM,
	CURRENCY,
	CODE_OF_LAWS,
	STATE_RELIGION,
	RELIGIOUS_LAW,
	BULK_TRADE,
	JURISPRUDENCE,
	BANKING,
	MANUFACTURED_TRADE,
	WAGE_LABOR,
	MINING,
	BRONZE_WORKING,
	INFANTRY_TACTICS,
	MILITARY_DRILL,
	LOGISTICS,
	METAL_CASTING,
	SCALE_ARMOR,
	IRON_WORKING,
	STEEL_WORKING,
	CHAINMAIL,
	BLAST_FURNACE,
	ALCHEMY,
	GUNPOWDER,
	POLYTHEISM,
	PRIESTHOOD,
	ASTRONOMY,
	ORGANISED_RELIGION,
	MONASTICISM,
	THEOLOGY,
	RELIGIOUS_LAW_TECH,
	MYSTICISM,
	SYNCRETISM,
	DIVINE_RIGHT,
	THEOCRACY,
	WRITING,
	ALPAHBET,
	MATHEMATICS,
	CARTOGRAPHY,
	LITERATURE,
	DRAMA,
	PHILOSOPHY,
	AESTHETICS,
	PATRONAGE,
	TIBETAN_UP,
	TOCHARIAN_UP,
	FUNAN_UP,
	SRIVIJAYAN_UP,
	STABILITY_STABLE,
	STABILITY_UNSTABLE,
	STABILITY_COLLAPSING,
	STABILITY_CHECK,
	ROMAN_EMPIRE
};

enum MyBuildings
{
	INVASION = 2,
	WALLS = 3,
	STABLE = 13,
	COURTHOUSE = 28,
	BUDDHIST_SHRINE = 98,
	HINDU_SHRINE = 103,
	GREAT_WALL = 161,
	TERRACOTTA = 162,
	GREAT_LIGHTHOUSE = 163,
	GREAT_LIBRARY = 164,
	TRAJANS_COLUMN = 165,
	COLLOSEUM = 166,
	ARCHIMEDES = 167,
	SYNTHESIS = 168,
	MINARET = 169,
	HOUSE_OF_WISDOM = 170,
	KHALID = 171,
	STUPA = 172,
	NALANDA = 173,
	HAGIA = 174,
	BAMIYAN = 175,
	DOME_OF_THE_ROCK = 176,
	UMAYYAD_MOSQUE = 177,
	IRON_PILLAR = 178,
	QALEH_DOKHTAR = 179,
	GRAND_CANAL = 180,
	BOROBUDUR = 181,
	THEODOSIAN_WALLS = 182,
	SHWEDAGON_PAYA = 183
};

enum MyArtStyles
{
	ARTSTYLE_EUROPEAN, // 0
	ARTSTYLE_ARABIAN, // 1
	ARTSTYLE_MIDDLE_EAST, // 2
	ARTSTYLE_MEDITERRANEAN, // 3
	ARTSTYLE_INDIA, // 4
	ARTSTYLE_EGYPT, // 5
	ARTSTYLE_ASIA, // 6
	ARTSTYLE_JAPAN, // 7
	ARTSTYLE_SOUTH_EAST_ASIA, // 8
	ARTSTYLE_AFRICA, // 9
	ARTSTYLE_PERSIAN // 10
};

#endif	// CVRHYES_H

extern int startingYear[NUM_MAJOR_PLAYERS];
extern int startingCalendarYear[NUM_MAJOR_PLAYERS];
extern bool startingEra[NUM_MAJOR_PLAYERS];
extern int maxTakenTiles[NUM_MAJOR_PLAYERS];
extern int warDistanceModifier[NUM_MAJOR_PLAYERS];
extern int warCoastalModifier[NUM_MAJOR_PLAYERS];
extern int inflationRate[NUM_MAJOR_PLAYERS];
extern int growthPercent[NUM_MAJOR_PLAYERS];
extern int productionPercent[NUM_MAJOR_PLAYERS];
extern int researchPercent[NUM_MAJOR_PLAYERS];
extern int greatPeoplePercent[NUM_MAJOR_PLAYERS];
extern int culturePercent[NUM_MAJOR_PLAYERS];
extern int distanceMaintenancePercent[NUM_MAJOR_PLAYERS];
extern int numCitiesMaintenancePercent[NUM_MAJOR_PLAYERS];
extern int compactEmpireModifier[NUM_MAJOR_PLAYERS];
extern int civSpreadFactor[MAX_PLAYERS][NUM_RELIGIONS];
extern int borders[NUM_MAJOR_LEADERS][NUM_MAJOR_LEADERS];
extern int attitudeMods[NUM_MAJOR_PLAYERS][NUM_MAJOR_PLAYERS];
extern int massacreProb[MAX_PLAYERS];
extern int buildProsecutorProb[NUM_MAJOR_PLAYERS];
extern int regionMap[EARTH_Y][EARTH_X];
extern int artStyleMap[EARTH_Y][EARTH_X];
//extern int settlersMaps[NUM_MAJOR_PLAYERS][EARTH_Y][EARTH_X];
extern int settlersMaps[NUM_CIV_DESC][EARTH_Y][EARTH_X]; // srpt
extern int turnPlayed[MAX_PLAYERS];
extern char uniquePower[NUM_MAJOR_PLAYERS][2][16];
extern char uniqueGoals[NUM_MAJOR_PLAYERS][3][18];
extern char rating[NUM_MAJOR_PLAYERS+6][6][15];
extern int barbRegions[NUM_BARB_REGIONS];